export const userConstant = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_CURRENT_USER_REQUEST: "GET_CURRENT_USER_REQUEST",
  GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_FAILURE: "GET_CURRENT_USER_FAILURE",

  GET_ACCOUNT_NUMBER_REQUEST: " GET_ACCOUNT_NUMBER_REQUEST",
  GET_ACCOUNT_NUMBER_SUCCESS: "GET_ACCOUNT_NUMBER_SUCCESS",
  GET_ACCOUNT_NUMBER_FAILURE: "GET_ACCOUNT_NUMBER_FAILURE",

  SENDEMAILFORGOTPASSWORD_REQUEST: "USERS_FORGOTPASSWORD_REQUEST",
  SENDEMAILFORGOTPASSWORD_SUCCESS: "USERS_FORGOTPASSWORD_SUCCESS",
  SENDEMAILFORGOTPASSWORD_FAILURE: "USERS_FORGOTPASSWORD_FAILURE",

  FORGOTPASSWORD_REQUEST: "FORGOTPASSWORD_REQUEST",
  FORGOTPASSWORD_SUCCESS: "FORGOTPASSWORD_SUCCESS",
  FORGOTPASSWORD_FAILURE: "FORGOTPASSWORD_FAILURE",

  LOGOUT: "LOGOUT",
  GET_BENEFICIARY_REQUEST: "GET_BENEFICIARY_REQUEST",
  GET_BENEFICIARY_SUCCESS: "GET_BENEFICIARY_SUCCESS",
  GET_BENEFICIARY_FAILURE: "GET_BENEFICIARY_FAILURE",

  UPDATEPASSWORD_REQUEST: "USERS_UPDATEPASSWORD_REQUEST",
  UPDATEPASSWORD_SUCCESS: "USERS_UPDATEPASSWORD_SUCCESS",
  UPDATEPASSWORD_FAILURE: "USERS_UPDATEPASSWORD_FAILURE",
};

// employee
export const employeeConstants = {
  REGISTERBANKACCOUN_REQUEST: "EMPLOYEES_REGISTER_BANKACCOUN_REQUEST",
  REGISTERBANKACCOUN_SUCCESS: "EMPLOYEES_REGISTER_BANKACCOUN_SUCCESS",
  REGISTERBANKACCOUN_FAILURE: "EMPLOYEES_REGISTER_BANKACCOUN_FAILURE",

  APPLYMONEY_REQUEST: "EMPLOYEES_APPLYMONEY_REQUEST",
  APPLYMONEY_SUCCESS: "EMPLOYEES_APPLYMONEY_SUCCESS",
  APPLYMONEY_FAILURE: "EMPLOYEES_APPLYMONEY_FAILURE",

  GET_CUSTOMER_REQUEST: "GET_CUSTOMER_REQUEST",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE: "GET_CUSTOMER_FAILURE",

  GET_CUSTOMER_LIST_REQUEST: "GET_CUSTOMER_LIST_REQUEST",
  GET_CUSTOMER_LIST_SUCCESS: "GET_CUSTOMER_LIST_SUCCESS",
  GET_CUSTOMER_LIST_FAILURE: "GET_CUSTOMER_LIST_FAILURE",

  GET_CUSTOMER_TRANSACTION_REQUEST: "GET_CUSTOMER_TRANSACTION_REQUEST",
  GET_CUSTOMER_TRANSACTION_SUCCESS: "GET_CUSTOMER_TRANSACTION_SUCCESS",
  GET_CUSTOMER_TRANSACTION_FAILURE: "GET_CUSTOMER_TRANSACTION_FAILURE",

  GET_CUSTOMER_USERID_REQUEST: "GET_CUSTOMER_USERID_REQUEST",
  GET_CUSTOMER_USERID_SUCCESS: "GET_CUSTOMER_USERID_SUCCESS",
  GET_CUSTOMER_USERID_FAILURE: "GET_CUSTOMER_USERID_FAILURE",
};

export const transactionConstants = {
  TRANSACTION_LOCAL_REQUEST: "USERS_TRANSACTION_LOCAL_REQUEST",
  TRANSACTION_LOCAL_SUCCESS: "USERS_TRANSACTION_LOCAL_SUCCESS",
  TRANSACTION_LOCAL_FAILURE: "USERS_TRANSACTION_LOCAL_FAILURE",
  TRANSFER_REQUEST: "USERS_ TRANSFER_REQUEST",
  TRANSFER_SUCCESS: "USERS_ TRANSFER_SUCCESS",
  TRANSFER_FAILURE: "USERS_ TRANSFER_FAILURE",

  TRANSACTION_LOCAL_RECEIVE_REQUEST: "USERS_TRANSACTION_LOCAL_RECEIVE_REQUEST",
  TRANSACTION_LOCAL_RECEIVE_SUCCESS: "USERS_TRANSACTION_LOCAL_RECEIVE_SUCCESS",
  TRANSACTION_LOCAL_RECEIVE_FAILURE: "USERS_TRANSACTION_LOCAL_RECEIVE_FAILURE",

  RECEIVE_REQUEST: "USERS_RECEIVE_REQUEST",
  RECEIVE_SUCCESS: "USERS_RsECEIVE_SUCCESS",
  RECEIVE_FAILURE: "USERS_RECEIVE_FAILURE",

  SAVE_RECEIVE_REQUEST: "USERS_SAVE_RECEIVE_REQUEST",
  SAVE_RECEIVE_SUCCESS: "USERS_ SAVE_RECEIVE_SUCCESS",
  SAVE_RECEIVE_FAILURE: "USERS_ SAVE_RECEIVE_FAILURE",

  EDIT_RECEIVE_REQUEST: "USERS_EDIT_RECEIVE_REQUEST",
  EDIT_RECEIVE_SUCCESS: "USERS_EDIT_RECEIVE_SUCCESS",
  EDIT_RECEIVE_FAILURE: "USERS_EDIT_RECEIVE_FAILURE",

  TRANSACTION_LINK_BANK_REQUEST: "TRANSACTION_LINK_BANK_REQUEST",
  TRANSACTION_LINK_BANK_SUCCESS: "TRANSACTION_LINK_BANK_SUCCESS",
  TRANSACTION_LINK_BANK_FAILURE: "TRANSACTION_LINK_BANK_FAILURE",

  VERIFY_OTP_LINK_BANK_REQUEST: "VERIFY_OTP_LINK_BANK_REQUEST",
  VERIFY_OTP_LINK_BANK_SUCCESS: "VERIFY_OTP_LINK_BANK_SUCCESS",
  VERIFY_OTP_LINK_BANK_FAILURE: "VERIFY_OTP_LINK_BANK_FAILURE",

  GET_LINK_BANK_REQUEST: " GET_LINK_BANK_REQUEST",
  GET_LINK_BANK_SUCCESS: "GET_LINK_BANK_SUCCESS",
  GET_LINK_BANK_FAILURE: "GET_LINK_BANK_FAILURE",

  DELETE_RECEIVER_REQUEST: "DELETE_RECEIVER_REQUEST",
  DELETE_RECEIVER_SUCCESS: "DELETE_RECEIVER_SUCCESS",
  DELETE_RECEIVER_FAILURE: "DELETE_RECEIVER_FAILURE",
};
export const deptConstants = {
  GET_REMIND_REQUEST: "GET_REMIND_REQUEST",
  GET_REMIND_SUCCESS: "GET_REMIND_SUCCESS",
  GET_REMIND_FAILURE: "GET_REMIND_FAILURE",

  GET_DEPT_REQUEST: "GET_DEPT_REQUEST",
  GET_DEPT_SUCCESS: "GET_DEPT_SUCCESS",
  GET_DEPT_FAILURE: "GET_DEPT_FAILURE",

  ADD_DEPT_REMIND_REQUEST: "ADD_DEPT_REMIND_REQUEST",
  ADD_DEPT_REMIND_SUCCESS: "ADD_DEPT_REMIND_SUCCESS",
  ADD_DEPT_REMIND_FAILURE: "ADD_DEPT_REMIND_FAILURE",

  EDIT_DEPT_REMIND_REQUEST: "EDIT_DEPT_REMIND_REQUEST",
  EDIT_DEPT_REMIND_SUCCESS: "EDIT_DEPT_REMIND_SUCCESS",
  EDIT_DEPT_REMIND_FAILURE: "EDIT_DEPT_REMIND_FAILURE",

  DELETE_DEPT_REMIND_REQUEST: "DELETE_DEPT_REMIND_REQUEST",
  DELETE_DEPT_REMIND_SUCCESS: "DELETE_DEPT_REMIND_SUCCESS",
  DELETE_DEPT_REMIND_FAILURE: "DELETE_DEPT_REMIND_FAILURE",

  GET_DEPT_NOTIFICATION_REQUEST: "GET_DEPT_NOTIFICATION_REQUEST",
  GET_DEPT_NOTIFICATION_SUCCESS: "GET_DEPT_NOTIFICATION_SUCCESS",
  GET_DEPT_NOTIFICATION_FAILURE: "GET_DEPT_NOTIFICATION_FAILURE",


};

export const historyConstants = {
  GET_HISTORY_PAYMENT_REQUEST: "GET_HISTORY_PAYMENT_REQUEST",
  GET_HISTORY_PAYMENT_SUCCESS: "GET_HISTORY_PAYMENT_SUCCESS",
  GET_HISTORY_PAYMENT_FAILURE: "GET_HISTORY_PAYMENT_FAILURE",
};
