export const userConstant = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  SENDEMAILFORGOTPASSWORD_REQUEST: "USERS_FORGOTPASSWORD_REQUEST",
  SENDEMAILFORGOTPASSWORD_SUCCESS: "USERS_FORGOTPASSWORD_SUCCESS",
  SENDEMAILFORGOTPASSWORD_FAILURE: "USERS_FORGOTPASSWORD_FAILURE",

  FORGOTPASSWORD_REQUEST: "USERS_FORGOTPASSWORD_REQUEST",
  FORGOTPASSWORD_SUCCESS: "USERS_FORGOTPASSWORD_SUCCESS",
  FORGOTPASSWORD_FAILURE: "USERS_FORGOTPASSWORD_FAILURE",
};
